# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ninaAdmin
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - private-net
  api:
    build: .
    container_name: auth_api
    # On laisse le Dockerfile gérer la commande de démarrage (migrations + start)
    restart: always
    environment:
      - DATABASE_URL="postgres://admin:ninaAdmin@postgres:5432/authService-db"
    ports:
      - '3002:3002'
    depends_on:
      - postgres
    networks:
      - private-net
      - reseau-web
networks:
  private-net:
    driver: bridge
  reseau-web:
    external: true

volumes:
  postgres:
